# Generated by Django 3.2.9 on 2022-01-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211230_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.DeleteModel(
            name='Myprofile',
        ),
    ]
